#!/usr/bin/env python3

# Toggles swapping of Ctrl and Caps Lock, preserving other xkb options.

from gi.repository import Gio

settings = Gio.Settings.new("org.gnome.desktop.input-sources")
options = settings.get_strv("xkb-options")

if "ctrl:swapcaps" in options:
    options.remove("ctrl:swapcaps")
else:
    options.append("ctrl:swapcaps")

settings.set_strv("xkb-options", options)
